### ISSUE TITLE
[SOLVED] C4 Errors (Limitation of # of Saves or Memory?)

### ISSUE THREAD

**Issue by bfluryx1234** [ClusterM/retroarch-clover#14] opened 2017-02-23 03:55 UTC
Ok... so the C4 error occurs when trying to save games. Specifically for me it seems to be when I try to save SNES games.

I have narrowed it down to the following:
1.I can have 18 saved SNES games (excluding battery backup) across as many folders as I want
2.When limit is reached I can still save games for all other systems!
3.Limit is not impacted if I remove ROMs
4.State Slot is set to '0' (not sure if this was the default?)
5.Previously opened a lot of games that seem to create .SRAM (not sure how to remove, but I have tons!)
6.Battery Backup Saves (i.e. Final Fantasy) do not seem to impact (at least creating an individual slot, now a brand new game being added might?!?!?)
7.I noticed (after a recent transfer) that one of the last games (when sorted by folder view on the PC) had the broken image thumbnail instead of a screenshot for the save state...

Using SNES 2010 Core.

I read somewhere else that another user seemed limited at 10. I am thinking we might be hitting that 30mb limit in some cache folder somewhere...

**Comment by bfluryx1234** [comment] 2017-02-23 07:24
I cross-posted this on the Hakchi Project: https://github.com/ClusterM/hakchi2/issues/132

However, I suspect this is the more appropriate place for it.  I'm pretty sure I've narrowed it down to SNES at this point... Let me know how I can help.

**Comment by ajmi982** [comment] 2017-02-26 17:35
I too have C4 issues. Using the latest build of RA and Hakchi - DKC2 C4 error.  Using SNES2005 core

**Comment by pcm720** [comment] 2017-02-26 19:08
C4 for SNES9x2010 fixed by using SNES9x2005 since it's caused by some bug in the core.
ajmi982, have you used SNES9x2010 before? I think you'll need to uninstall hakchi and do a factory reset

**Comment by ajmi982** [comment] 2017-02-26 19:32
Yes I had used snes2010 and I did a clean flash. The clean flash didn't kill save states though. So that spear is gone till we get full system.access. I even deleted my SNES save states from the mini GUI. Still screwed with C4 :( boom! Lol

**Comment by pcm720** [comment] 2017-02-26 19:37
Try factory reset

**Comment by ajmi982** [comment] 2017-02-26 22:38
How do I do a factory reset?? Also I'll lose ever single save that way right? That would suck!!

**Comment by pcm720** [comment] 2017-02-26 22:39
Yes, but you are getting C4 anyway, so what's there to lose?

**Comment by ajmi982** [comment] 2017-02-26 22:41
We need a way to extract our saves. Didn't cluster say this was possible? Would hate to have to play through entire games again that I'm close to beating.

**Comment by pcm720** [comment] 2017-02-26 22:44
There is a way to extract your saves, but it involves using UART (for now). More convenient solution won't be ready anytime soon. I guess your only option in this case is to remove games you don't play.

**Comment by bfluryx1234** [comment] 2017-02-28 15:35
PCM720 - Was it creating a 5mb save state for every game saved?!?!?  That would make sense as I could only load about 220mb of games and have 18 save states (90mb) for a total of 310mb!!!

You don't have to do a full factory reset, but you do have to delete all the old SNES states if that is the case.  Will 2010 save states load in 2005?  Maybe we can load up the old save states and save them again in the 2005 format?

**Comment by pcm720** [comment] 2017-02-28 15:37
Yes, it did create 5 MB savestate for every game I tried (2 :)).

Someone tried to load 2010 savestates in 2005, it didn't work.

**Comment by bfluryx1234** [comment] 2017-02-28 15:39
Well that sucks... at least the issue is figured out.  It was driving me crazy.  Thanks!

**Closed** 2017-03-02 05:45 UTC
