### ISSUE TITLE
FDS Games not Saving with Nestopia

### ISSUE THREAD

**Issue by raccoonmario3** [ClusterM/retroarch-clover#23] opened 2017-02-25 06:30 UTC
I played through Super Mario Bros: The Lost Levels (Japanese SMB2), and got one star on the title screen. Normally, the star should still be there when I go back to the NES Mini's menu and reload the game. Instead, the star was gone, as if the disk image was brand new. The purpose of the stars is that when you get 8, for beating the game 8 times, you can then access worlds A-D, by holding A and pressing start. The game obviously won't work with FCEUmm, since it doesn't support FDS games. Right now, the only way I can save FDS games is to use the save-state functionality. Is there any way to get a proper in-game save working? NES cartridge games like both Zelda games seem to save just fine, and as mentioned before, save states work.

**Comment by pcm720** [comment] 2017-02-25 14:28
Are you using the latest release?
I've tried saving in Zelda no Densetsu, and it works fine.
I've created the profile, restarted the game and was able to load my profile again from file select screen.

**Comment by raccoonmario3** [comment] 2017-02-25 19:02
I am using the latest release of the RetroArch .hmod. I will test FDS Zelda and see if it saves properly. Maybe the problem is specific to the Japanese SMB2. Have you tested that game?

**Comment by pcm720** [comment] 2017-02-25 20:52
No, I (sadly) don't have the time to play through the whole SMB2.
If it works for Zelda, it should work for SMB2. If it doesn't, the problem is with the core itself, and there's nothing we can do about it.

**Comment by raccoonmario3** [comment] 2017-02-26 18:40
I tested FDS Zelda on the NESCE, and I noticed that if I made a save file, exited the game, and then re-loaded it, my save was still there. It also stayed if I went to another game and then back. The save data only disappears after I turn off the console, and then turn it back on. So no, Zelda does not save either, unless I leave the console on forever, or I use save states.

**Comment by pcm720** [comment] 2017-02-26 18:42
Okay, now that's a problem.
Thanks, I'll look into it.

**Comment by pcm720** [comment] 2017-02-26 23:42
I've fixed the issue. Fix will be included in the next release

**Closed** 2017-03-01 17:30 UTC
