### ISSUE TITLE
[SNES mini] Return to game select after launching game

### ISSUE THREAD

**Issue by Agmorenard** [ClusterM/retroarch-clover#77] opened 2017-10-08 08:12 UTC
Greeting, i have one problem.

After a launch a game, using retroarch, when i push any button, it returning back to game select with ability to save "save state". It's like, after pushing button, it automatically "pushes" reset button. What can be a problem there?
For some information, i'm using same modules, that i downloaded from here. And tried to launch Sega and SNES game.

**Comment by LanceloteHK** [comment] 2017-10-08 17:22
Same here. I am using Super Famicom mini. I tried the Street Fighter 2 zero japan ver rom. The game runs fine, but when i press any button it pops out to the main menu. Any other game runs with '--retroarch' have same issue.

**Comment by progranadegrinder** [comment] 2017-10-08 20:58
I've found that if you use the CloverApp, everything works fine, it's just when you add a ROM to the actual list of games that any button will close it.

**Comment by buggii** [comment] 2017-10-08 22:27
I also have this issue.
The "return to main menu" happens 2-3 seconds after i press one of the pad buttons (no matter which one); it happens with retroarch-launched games only.

Tried to uninstall everything+factory reset and re-patch kernel: always the same problem.

**Comment by buggii** [comment] 2017-10-09 11:21
I did some more tests to dig out the problem (tests done with only genesis plus gx core):

retroarch 0.7 + genesis plus gx 0.7 = bug is not present, Mega Drive game starts and works fine (no exit when pressing pad buttons) but when exiting I have C8 error; need to remove USB power to turn off the console and after reboot it asks for language select.

retroarch 0.7 + genesis plus gx 0.8 = game does not start (black screen).

retroarch 0.8 + genesis plus gx 0.7 = bug is present (game starts and exits at each butto press).

I suppose the problem is inside retroarch core, need to dig it out.

**Comment by Agmorenard** [comment] 2017-10-09 11:43
I just don't understand, why so many people have no problem with retroarch, while we have this problem. There are differences between each SNES mini?

**Comment by buggii** [comment] 2017-10-09 12:00
My best guess is that the problem is present in people who modded with early hakchi versions but there are reports of people haveing the problem even if they started "hacking" with hakchi2 2.20 so... dunno ! :P

**Comment by Agmorenard** [comment] 2017-10-09 12:02
Actually, i didn't hack SNES with early hakchi. I hacked with official 2.20, that was released yesterday. So, I'm one of them :P

**Comment by buggii** [comment] 2017-10-09 12:12
Can this be the problem: https://i.imgur.com/QXUwuLX.png ?

File is: user_mods 0.8/retroarch/bin/retroarch-clover-child

**Comment by buggii** [comment] 2017-10-09 12:31
I think the "bug" is in that piece of code; removing all this part:

[code]
# Playing games until reset pressed
while [ true ]; do
  kill -0 $rpid 2> /dev/null || break
  kill -0 $reset_pid 2> /dev/null || break
  kill -0 $power_pid 2> /dev/null || break
  if [ ! -z "$demo" ]; then
    # Exit on any button
    kill -0 $anybutton_pid 2> /dev/null || break
    # Or after some time
    ts2=$(date +"%s")
    tp=$((ts2 - ts))
    [ "$tp" -ge "$demo_time" ] && break
  fi
done

kill $rpid 2> /dev/null
kill -KILL $reset_pid 2> /dev/null
kill -KILL $power_pid 2> /dev/null
[ ! -z "$demo" ] && kill -KILL $anybutton_pid 2> /dev/null

[ ! -z "$save" ] && mkdir -p $(dirname "$save")
[ ! -z "$sram" ] && mkdir -p $(dirname "$sram")
[ ! -z "$screenshot" ] && mkdir -p $(dirname "$screenshot")
[/code]

Totally removing that part solve the problem (but makes the game crash when home button is pressed); is someone able to fix this part of code ? The problem, i sum it up, is that when launching a retroarch game at each button press the game exits to SNES Mini main menu.

Thanks in advance !

**Comment by Agmorenard** [comment] 2017-10-09 12:34
I'm not a good programmer, my i'm curious about this raw:

**Comment by buggii** [comment] 2017-10-09 12:36
I think it refers to "demo mode" which is halted when you press a button but I don't know if it is properly coded.

**Comment by Agmorenard** [comment] 2017-10-09 13:02
I think so too, but i dunno about '!'... It's more like NOT demo

**Comment by buggii** [comment] 2017-10-09 13:10
Someone should bring this thread to Cluster attention ;)

**Comment by FierceLog** [comment] 2017-10-09 14:51
I am having this issue as well.  All of the controller buttons seem to be mapped to "Reset" so it goes back to the menu.  On some games I can quickly hit "Select" and watch it move to the next option, but within a second it goes back to the Menu like I hit "Reset" aka "Suspend".

**Comment by sebabadi** [comment] 2017-10-09 14:56
Same here! A fix is needed!

**Comment by FierceLog** [comment] 2017-10-09 15:43
This looks like a configuration error: Try this: are you using something like this for the commandline for the game: /bin/nes /usr/share/games/CLV-H-THQIF/1942_(Japan__USA).nes

If so, make sure you don't have "--retroarch" at the end.  It's not necessary and I think it causes this issue.    I tested it. Anyone can confirm?

**Comment by FierceLog** [comment] 2017-10-09 16:18
Here's what fixed it for me:  I checked the box marked "Use button combination to reset" under Settings -> Controller Hacks. 

First I flashed the custom kernel, then I installed the extra module for RetroArch 0.8, then I checked the box mentioned above and clicked "Save Settings to SNES Now".  Finally I synchronized my selected games.

For now it looks like "Use button combination to reset" under Settings -> Controller Hacks is required if you are using RetroArch mod.

**Comment by Agmorenard** [comment] 2017-10-09 16:57
OMG, Thank you so much, FierceLog. It worked for me!
Just to simplify your post: Checking "Use button combination to reset" under Settings -> Controller Hacks really fix that problem. Just do not forget to save it to SNES)

**Comment by progranadegrinder** [comment] 2017-10-09 17:48
Are you guys having issues with save games not staying?

**Comment by buggii** [comment] 2017-10-09 19:09
Good catch FierceLog ! It worked for me too !

**Comment by ClusterM** [comment] 2017-10-09 20:07
I need more info. Maybe someone can let me see it via teamviewer?

**Comment by Agmorenard** [comment] 2017-10-09 20:09
What exactly "it"?

**Comment by ClusterM** [comment] 2017-10-09 20:20
I need to login via telnet, check /dev/input/event* files, edit RetroArch script to add logs, check logs.

**Comment by ClusterM** [comment] 2017-10-09 20:24
Oh, I found problem. Will be fixed soon.

**Comment by buggii** [comment] 2017-10-09 21:10
Thank you Cluster !

**Comment by ClusterM** [comment] 2017-10-09 21:53
Fixed and released. Download and install new version. Sorry for that.

**Comment by FierceLog** [comment] 2017-10-10 00:48
Awesome! Thanks ClusterM!

**Closed** 2017-10-10 07:18 UTC
